from __future__ import annotations

# Official vendor endpoints only. Users paste their own relay into 自定义.
PRESETS: list[dict] = [
    {
        "id": "custom",
        "label": "自定义",
        "name": "",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "",
        "website": "",
        "iconColor": "#64748b",
        "models": [],
    },
    {
        "id": "openai",
        "label": "OpenAI",
        "name": "OpenAI",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "https://api.openai.com/v1",
        "website": "https://platform.openai.com",
        "iconColor": "#10a37f",
        "models": [{"cursorName": "openai-main", "upstreamId": "gpt-4o"}],
    },
    {
        "id": "anthropic",
        "label": "Anthropic",
        "name": "Anthropic",
        "protocol": "anthropic",
        "authStyle": "x-api-key",
        "baseUrl": "https://api.anthropic.com",
        "website": "https://console.anthropic.com",
        "iconColor": "#d97706",
        "models": [{"cursorName": "anthropic-sonnet", "upstreamId": "claude-sonnet-4-5"}],
    },
    {
        "id": "deepseek",
        "label": "DeepSeek",
        "name": "DeepSeek",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "https://api.deepseek.com/v1",
        "website": "https://platform.deepseek.com",
        "iconColor": "#4d6bfe",
        "models": [{"cursorName": "deepseek-chat-relay", "upstreamId": "deepseek-chat"}],
    },
    {
        "id": "kimi",
        "label": "Kimi",
        "name": "Kimi",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "https://api.moonshot.cn/v1",
        "website": "https://platform.moonshot.cn",
        "iconColor": "#111827",
        "models": [{"cursorName": "kimi-auto", "upstreamId": "moonshot-v1-auto"}],
    },
    {
        "id": "glm",
        "label": "智谱 GLM",
        "name": "智谱 GLM",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "https://open.bigmodel.cn/api/paas/v4",
        "website": "https://open.bigmodel.cn",
        "iconColor": "#2563eb",
        "models": [{"cursorName": "glm-flash", "upstreamId": "glm-4-flash"}],
    },
    {
        "id": "minimax",
        "label": "MiniMax",
        "name": "MiniMax",
        "protocol": "openai",
        "authStyle": "bearer",
        "baseUrl": "https://api.minimaxi.com/v1",
        "website": "https://www.minimaxi.com",
        "iconColor": "#e11d48",
        "models": [{"cursorName": "minimax-text", "upstreamId": "MiniMax-Text-01"}],
    },
]

ICON_COLORS = (
    "#2563eb",
    "#10b981",
    "#f59e0b",
    "#8b5cf6",
    "#ec4899",
    "#06b6d4",
    "#ef4444",
    "#111827",
    "#64748b",
    "#14b8a6",
)
